stages:
  - test
  - package
  - publish
  - deploy_to_staging

cache:
  paths:
    - ./target

test:
  stage: test
  script:
    - mvn test

package:
  stage: package
  script:
    - mvn package
  only:
    - master

publish:
  stage: publish
  script:
    - aws s3 cp target/example-0.1-SNAPSHOT.jar s3://tcs-repo/
  only:
    - master

deploy_to_staging:
  stage: deploy_to_staging
  script: >
    aws --region eu-west-1 lambda update-function-code --function-name LambdaFunction --s3-bucket tcs-repo --s3-key example-0.1-SNAPSHOT.jar
  only:
    - master
